# Database configuration
# 
# For production (Oracle):
# db.driver=oracle.jdbc.OracleDriver
# db.url=jdbc:oracle:thin:@prodserver:1521:BIGCORP
# db.username=bigcorp_app
# db.password=<see_ops_team>
#
# For development (HSQLDB):
db.driver=org.hsqldb.jdbc.JDBCDriver
db.url=jdbc:hsqldb:mem:bigcorpdb
db.username=sa
db.password=
