# MQ Configuration
#
# For production (IBM MQSeries):
# mq.broker.url=tcp://mqserver.bigcorp.internal:61616
# mq.queue.manager=BIGCORP.QM
# mq.channel=BIGCORP.SVRCONN
#
# For development (embedded ActiveMQ):
mq.broker.url=vm://localhost?broker.persistent=false
